/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.awt.HeadlessException;
import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author Cihangir
 */
public class Register extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tcnum = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        adsoyad = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        password = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        telnum = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        birthdate = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel1.setText("REGISTER FORM");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 12, -1, -1));

        jLabel3.setText("TC Numarası:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 92, -1));

        jLabel4.setText("Email:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 92, -1));

        jLabel5.setText("Telefon Numarası:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 110, -1));

        jLabel6.setText("Ad Soyad:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 92, -1));

        tcnum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tcnumActionPerformed(evt);
            }
        });
        getContentPane().add(tcnum, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 125, -1));

        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        getContentPane().add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 125, -1));

        adsoyad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adsoyadActionPerformed(evt);
            }
        });
        getContentPane().add(adsoyad, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 125, -1));

        jLabel7.setText("Şifre:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 92, -1));
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, 125, -1));

        jLabel8.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        jLabel8.setText("BACK");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(494, 12, -1, -1));
        getContentPane().add(telnum, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 125, -1));

        jLabel10.setText("Doğum Tarihi:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 110, -1));

        birthdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                birthdateActionPerformed(evt);
            }
        });
        getContentPane().add(birthdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, 125, -1));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(102, 0, 0));
        jButton1.setText("REGISTER");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(433, 334, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tcnumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tcnumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tcnumActionPerformed

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        LoginScreen obj=new LoginScreen();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel8MouseClicked

    private void adsoyadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adsoyadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adsoyadActionPerformed

    private void birthdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_birthdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_birthdateActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
            
            Class.forName("com.mysql.cj.jdbc.Driver");
          
                //Database connection komutu    
                Connection Conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/Bank","root","Bceobaaaaa111.");
                String query1="Select Count(musteriid) from musteri";
                Statement state1=Conn.createStatement();
                ResultSet result1=state1.executeQuery(query1);
                result1.next();
                int x=Integer.parseInt(result1.getString("Count(musteriid)"));
                
                String query2="Select Count(registerid) from register";
                Statement state2=Conn.createStatement();
                ResultSet result2=state2.executeQuery(query2);
                
                result2.next();
                
                
                int y=Integer.parseInt(result2.getString("Count(registerid)"));
                int z=x+y+1;
                String registerid=String.valueOf(z);
                
                String sql="insert into register values (?,?,?,?,?,?,?)";
                PreparedStatement ptstmt=Conn.prepareStatement(sql);//databasedeki register tablosuna ekleme
                ptstmt.setString(1, registerid);
                ptstmt.setString(2, adsoyad.getText());
                ptstmt.setString(3, tcnum.getText());
                ptstmt.setString(4, telnum.getText());
                ptstmt.setString(5, email.getText());
                ptstmt.setString(6, birthdate.getText());
                ptstmt.setString(7, password.getText());
                ptstmt.executeUpdate();
                
                JOptionPane.showMessageDialog(null, "Kayıt Talebi Alındı.");
            
        
        }catch(HeadlessException | ClassNotFoundException | SQLException e)
        {
            
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adsoyad;
    private javax.swing.JTextField birthdate;
    private javax.swing.JTextField email;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField password;
    private javax.swing.JTextField tcnum;
    private javax.swing.JTextField telnum;
    // End of variables declaration//GEN-END:variables
}
