import java.sql.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Cihangir
 */
public class RepMain extends javax.swing.JFrame {

    /**
     * Creates new form RepMain
     */
    public RepMain() {
        initComponents();
    }

    RepMain(String username) {
        //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        this();
        
        textField.setText(username);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        textField = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jButton6 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        adsoyad = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tcnum = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        telnum = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        birthdate = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        pass = new javax.swing.JPasswordField();
        jButton13 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton14 = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel1.setText("MANAGER MENU");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 25, -1, -1));

        jButton1.setText("Müşteri Silme");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 70, 110, -1));

        jButton2.setText("Müşteri Bilgileri");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 109, 120, -1));

        jButton3.setText("Müşteri Genel");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 149, 110, -1));

        jButton4.setText("Talepler");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 189, 110, -1));

        jButton5.setText("İşlem Dökümü");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 229, 110, -1));
        getContentPane().add(textField, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 309, 75, 16));

        jLabel2.setText("Müşteriler :");

        jScrollPane1.setViewportView(jList1);

        jButton6.setText("Sil");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(jButton6)))
                .addContainerGap(146, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton6)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(101, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab1", jPanel1);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("Müşteri Numarası:");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 23, -1, -1));

        jButton7.setText("Güncelle");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 273, -1, -1));

        jButton8.setText("Bul");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, -1, -1));

        jLabel4.setText("Ad Soyad:");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 74, -1, -1));
        jPanel3.add(adsoyad, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 74, 80, 16));

        jLabel6.setText("TC Numarası:");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 108, -1, -1));
        jPanel3.add(tcnum, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 108, 80, 16));

        jLabel8.setText("Tel Numarası:");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 148, -1, -1));

        jLabel9.setText("Email:");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 182, 72, -1));

        jLabel10.setText("Doğum Tarihi:");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 72, -1));

        jLabel11.setText("Password:");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 62, -1));
        jPanel3.add(telnum, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 148, 80, 16));
        jPanel3.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 182, 80, 16));
        jPanel3.add(birthdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 216, 80, 16));
        jPanel3.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, 71, -1));
        jPanel3.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 71, -1));
        jPanel3.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 71, -1));
        jPanel3.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, 70, -1));
        jPanel3.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, 70, -1));
        jPanel3.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 70, -1));

        pass.setEditable(false);
        pass.setBorder(null);
        pass.setSelectedTextColor(new java.awt.Color(242, 242, 242));
        pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passActionPerformed(evt);
            }
        });
        jPanel3.add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 80, -1));

        jButton13.setText("Müşteriler");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, -1, -1));

        jPanel3.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 80, -1));

        jTabbedPane1.addTab("tab2", jPanel3);

        jScrollPane2.setViewportView(jList2);

        jLabel5.setText("Müşteriler:");

        jLabel7.setText("Seçilen Müşterinin Hesapları:");

        jButton9.setText("Bul");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Hesap No", "Hesap Türü", "Bakiye"
            }
        ));
        jScrollPane5.setViewportView(Table);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jButton9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jButton9)
                .addContainerGap(133, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab3", jPanel4);

        jLabel13.setText("Hesap Açma Talepleri:");

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Talep No", "Müşteri No", "Hesap Türü"
            }
        ));
        jScrollPane6.setViewportView(jTable3);

        jButton11.setText("Yenile");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setText("Kabul Et");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel13))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel13)
                .addGap(28, 28, 28)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jButton11)
                        .addGap(72, 72, 72)
                        .addComponent(jButton12)))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab4", jPanel5);

        jLabel12.setText("Müşteri Numarası seçiniz:");

        jButton10.setText("Getir");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "İşlem No", "Müşteri No", "Kaynak ", "Hesap", "İşlem", "Tutar"
            }
        ));
        jScrollPane3.setViewportView(jTable2);

        jButton14.setText("Müşteri");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton14)
                .addGap(12, 12, 12))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jButton14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton10)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("tab5", jPanel6);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, -39, 420, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
            jTabbedPane1.setSelectedIndex(0);
            try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection Conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/Bank", "root", "Bceobaaaaa111.");
            
            DefaultListModel dlm=new DefaultListModel();
            String temsilci=textField.getText();
            String query="Select musteriid from musteri where temsilciid="+temsilci;
            
            Statement state=Conn.createStatement();
            ResultSet result=state.executeQuery(query);
            
            while(result.next())
            {
                String yaz=result.getString("musteriid");
                dlm.addElement(yaz);
            }
            jList1.setModel(dlm);
            
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(accoountpage.class.getName()).log(Level.SEVERE, null, ex);
        }
        
            
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
            jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
            jTabbedPane1.setSelectedIndex(2);
            try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection Conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/Bank", "root", "Bceobaaaaa111.");
            
            
            DefaultListModel dlm=new DefaultListModel();
            String temsilci=textField.getText();
            String query="Select musteriid from musteri where temsilciid="+temsilci;
            
            Statement state=Conn.createStatement();
            ResultSet result=state.executeQuery(query);
            
            while(result.next())
            {
                String yaz=result.getString("musteriid");
                dlm.addElement(yaz);
            }
            jList2.setModel(dlm);
            
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(accoountpage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
            jTabbedPane1.setSelectedIndex(3);
            
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
            jTabbedPane1.setSelectedIndex(4);            
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
            try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection Conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/Bank", "root", "Bceobaaaaa111.");
            
            //Müşteri temsilcisi müşteri silip kendi müşteri sayısını günceller
            String musteriid=jList1.getSelectedValue();
            
            String query="delete from musteri where musteriid="+musteriid;
            Statement state=Conn.createStatement();
            state.executeUpdate(query);
            
            String temsilci=textField.getText();
            String query2="Select Count(musteriid) from musteri where temsilciid="+temsilci;
            
            Statement state2=Conn.createStatement();
            ResultSet result2=state2.executeQuery(query2);
            result2.next();
            String sayi=result2.getString("Count(musteriid)");
            int musterisayisi=Integer.parseInt(sayi);
            
            String temsilciupdate="update temsilci SET musteriid="+musterisayisi+" where temsilciid="+temsilci;
            Statement state3=Conn.createStatement();
            state3.executeUpdate(temsilciupdate);
            
            JOptionPane.showMessageDialog(null, "İşlem Başarılı");
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(accoountpage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton6MouseClicked

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
            try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection Conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/Bank", "root", "Bceobaaaaa111.");
            
            String musteriid=jTextField1.getSelectedItem().toString();
            String query="Select * from musteri where musteriid='"+musteriid+"'";
            Statement state=Conn.createStatement();
            ResultSet result=state.executeQuery(query);
            result.next();
            String yaz1=result.getString("musteriad");
            String yaz2=result.getString("musteritc");
            String yaz3=result.getString("musteritel");
            String yaz4=result.getString("musteriemail");
            String yaz5=result.getString("musteribirthdate");
            String yaz6=result.getString("password");
            adsoyad.setText(yaz1);
            tcnum.setText(yaz2);
            telnum.setText(yaz3);
            email.setText(yaz4);
            birthdate.setText(yaz5);
            pass.setText(yaz6);
            
            } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(accoountpage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
            try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection Conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/Bank", "root", "Bceobaaaaa111.");
            
            String musteriid=jTextField1.getSelectedItem().toString();
            
            String güncel1=jTextField2.getText();
            String güncel2=jTextField3.getText();
            String güncel3=jTextField4.getText();
            String güncel4=jTextField5.getText();
            String güncel5=jTextField6.getText();
            String güncel6=jTextField7.getText();
            Statement state2=Conn.createStatement();
            
            String query2="update musteri SET musteriad='"+güncel1+"' where musteriid='"+musteriid+"'";
            state2.executeUpdate(query2);
            query2="update musteri SET musteritc='"+güncel2+"' where musteriid='"+musteriid+"'";
            state2.executeUpdate(query2);
            query2="update musteri SET musteritel='"+güncel3+"' where musteriid='"+musteriid+"'";
            state2.executeUpdate(query2);
            query2="update musteri SET musteriemail='"+güncel4+"' where musteriid='"+musteriid+"'";
            state2.executeUpdate(query2);
            query2="update musteri SET musteribirthdate='"+güncel5+"' where musteriid='"+musteriid+"'";
            state2.executeUpdate(query2);
            query2="update musteri SET password='"+güncel6+"' where musteriid='"+musteriid+"'";
            state2.executeUpdate(query2);
            
            JOptionPane.showMessageDialog(null, "Güncelleme Başarılı.");
            } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(accoountpage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection Conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/Bank", "root", "Bceobaaaaa111.");
           
            String musteriid=jList2.getSelectedValue();
            String query="Select hesapid,parabirimiid,bakiye from hesap where musteriid="+musteriid;
            Statement state=Conn.createStatement();
            ResultSet result=state.executeQuery(query);
            
            DefaultTableModel dlm=(DefaultTableModel)Table.getModel();
            while(result.next())
            {
                String yaz1=result.getString("hesapid");
                String yaz2=result.getString("parabirimiid");        
                String yaz3=result.getString("bakiye");
                
                String Data[]={yaz1,yaz2,yaz3};
                dlm.addRow(Data);
            }
            Table.setModel(dlm);
            
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(accoountpage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
            try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection Conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/Bank", "root", "Bceobaaaaa111.");
           
            String musteriid=jComboBox1.getSelectedItem().toString();
            
            String query="Select * from islem where musteriid="+musteriid;
            Statement state=Conn.createStatement();
            ResultSet result=state.executeQuery(query);
            DefaultTableModel dlm=(DefaultTableModel)jTable2.getModel();
            while(result.next())
            {
                String yaz1=result.getString("islemid");
                String yaz2=result.getString("musteriid");        
                String yaz3=result.getString("kaynakhesap");
                String yaz4=result.getString("hedefhesap");
                String yaz5=result.getString("islem");
                String yaz6=result.getString("tutar");
                String Data[]={yaz1,yaz2,yaz3,yaz4,yaz5,yaz6};
                dlm.addRow(Data);
            }
            
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(accoountpage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
            try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection Conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/Bank", "root", "Bceobaaaaa111.");
            
            String temsilci=textField.getText();
            String query="Select musteriid from musteri where temsilciid="+temsilci;
            
            Statement state=Conn.createStatement();
            ResultSet result=state.executeQuery(query);
            DefaultTableModel dlm=(DefaultTableModel)jTable3.getModel();
            jTable3.clearSelection();
            while(result.next())
            {   String musteriid=result.getString("musteriid");
                String query2="Select * from requests where customerid="+musteriid;
                Statement state2=Conn.createStatement();
                ResultSet result2=state2.executeQuery(query2);
                while(result2.next())
                {
                    String yaz1=result2.getString("requestid");
                    String yaz2=result2.getString("customerid");       
                    String yaz3=result2.getString("parabirimiid");
                    String data[]={yaz1,yaz2,yaz3};
                    dlm.addRow(data);
                }
            }
            
            
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(accoountpage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
             try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection Conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/Bank", "root", "Bceobaaaaa111.");
            
            String temsilci=textField.getText();
            String query="Select musteriid from musteri where temsilciid="+temsilci;
            
            Statement state=Conn.createStatement();
            ResultSet result=state.executeQuery(query);
            
            while(result.next())
            {
                String yaz=result.getString("musteriid");
                jTextField1.addItem(yaz);
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(accoountpage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
            try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection Conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/Bank", "root", "Bceobaaaaa111.");
            
            String temsilci=textField.getText();
            String query="Select musteriid from musteri where temsilciid="+temsilci;
            
            Statement state=Conn.createStatement();
            ResultSet result=state.executeQuery(query);
            
            while(result.next())
            {
                String yaz=result.getString("musteriid");
                jComboBox1.addItem(yaz);
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(accoountpage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
            try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection Conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/Bank", "root", "Bceobaaaaa111.");
            DefaultTableModel dlm=(DefaultTableModel)jTable3.getModel();
            String query="Select Count(musteriid) from hesap";
            Statement state=Conn.createStatement();
            ResultSet result=state.executeQuery(query);
            result.next();
            int hesapno=Integer.parseInt(result.getString("Count(musteriid)"));
            hesapno=hesapno+1;
            String hesapid=String.valueOf(hesapno);
            //Temsilci arayüzden seçtiği hesabı hesap tablosuna ekler
            int row=jTable3.getSelectedRow();
            String requestid=jTable3.getValueAt(row, 0).toString();
            String yaz2=jTable3.getValueAt(row, 1).toString();
            String yaz3=jTable3.getValueAt(row, 2).toString();
            dlm.removeRow(row);
            String zero ="0";
            String query2="insert into hesap values (?,?,?,?,?)";
            PreparedStatement state2=Conn.prepareStatement(query2);
            state2.setString(1, hesapid);
            state2.setString(2, yaz2);
            state2.setString(3, yaz3);
            state2.setString(4, "");
            state2.setString(5, zero);
            state2.executeUpdate();
            
            String query3="delete from requests where requestid="+requestid;
            Statement state3=Conn.createStatement();
            state3.executeUpdate(query3);
            
            
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(accoountpage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton12ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RepMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RepMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RepMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RepMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RepMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Table;
    private javax.swing.JLabel adsoyad;
    private javax.swing.JLabel birthdate;
    private javax.swing.JLabel email;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JComboBox<String> jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JPasswordField pass;
    private javax.swing.JLabel tcnum;
    private javax.swing.JLabel telnum;
    private javax.swing.JLabel textField;
    // End of variables declaration//GEN-END:variables
}
